### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by ppiekarczyk** [chenglou/react-radio-group#10]
Hey, 

Curious why are wrapping this in a function and then returning React.createClass. Do you mind explaining why I'd want to do that?

Thank you, 
Peter
```
function radio(name, selectedValue, onChange) {
  return React.createClass({
    render: function() {
      return (
        <input
          {...this.props}
          type="radio"
          name={name}
          checked={this.props.value === selectedValue}
          onChange={onChange.bind(null, this.props.value)} />
      );
    }
  });
}
```

**Comment by chenglou** [comment]
I need to rely on the closure of `name`, `selectedValue` and `onChange`. Otherwise, how would you pass these props to the input? Passing it in two steps (prepare a half made input, pass as argument and let the user splat more stuff onto it) isn't valid because it complicates the logic and is really dirty.

If you're approaching this as a perf question, this isn't expensive considering the use-cases. Will be even less so when react adopts [functions as components](https://github.com/facebook/react/pull/3995) so it'll be even lighter. I could have memorized the results like so: https://twitter.com/ronaldchanou/status/611385701679001602. But currently it's fine.

**Comment by ppiekarczyk** [comment]
Hey, 

I appreciate the response! I am used to something similar to this, which is why I wanted to ask

```javascript
// ...
{{children && <ReactRadioGroup name={this.props.name} selectedValue={this.props.selectedValue} /> 
// ...
```

**Comment by chenglou** [comment]
Yes, but this is different than that. There's no similarity between the two beside the fact that one uses `&&` visually and the other is `=>`. The latter is a function, in case that wasn't clear.

I'll close this now since it's not a real issue. But feel free to ask more!
