### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by damassi** [chenglou/react-radio-group#6]
It would be nice to have this option

**Comment by chenglou** [comment]
Late update: I've finally gotten around updating this library with a new API that's much cleaner (the new source code is like 30 lines only now, check it out!). I've talked to @jergason, who holds the name `react-radio-group` on npm, which is a fork of this library with an additional package.json.

While I'm at it, I'm also dropping Bower support since everyone's moving onto npm + browserify/webpack now (?). If any of you are against that I'll put bower back (don't really want to though).

**Comment by chenglou** [comment]
Done!

**Comment by josdejong** [comment]
Thanks. 

I don't use bower, just npm for everything, so it's totally fine with me.
